// src/components/cards/ClikcPickCard.vue
<script setup lang="ts">
</script>

<template>
  <div
    class="hidden lg:block w-64 mt-4 p-4 bg-gradient-to-b from-white to-[#EFEFEF] border-2 border-white rounded-md mb-4"
  >
    <h2 class="text-[21px] font-bold text-[#EC1E24] text-center">
      CS ClickPick
    </h2>

    <p class="text-sm text-[#282529] mt-2 text-center">
      Identify verified online universities and compare your favourite
      universities with a single click.
    </p>

    <div class="flex justify-center mt-4">
      <img src="/logo/Group.svg" alt="CS ClickPick Logo" />
    </div>

    <div class="flex justify-center mt-4">
      <button
        class="bg-[#EC1E24] text-white px-4 py-2 rounded hover:bg-[#EC1E24] text-base"
      >
        Start Now!
      </button>
    </div>
  </div>
</template>

// src/components/cards/clikcPickCard.tsx
export const CSClickPickCard = () => (
  <div className="hidden lg:block w-64 mt-4 p-4 bg-gradient-to-b from-white to-[#EFEFEF] border-2 border-white  rounded-md mb-4">
    <h2 className="text-[21px] font-bold text-[#EC1E24] text-center">
      CS ClickPick
    </h2>
    <p className="text-sm text-[#282529] mt-2 text-center">
      Identify verified online universities and compare your favourite
      universities with a single click.
    </p>
    <div className="flex justify-center mt-4">
      <img src="/logo/Group.svg" />
    </div>
    <div className="flex justify-center mt-4">
      <button className="bg-[#EC1E24] text-white px-4 py-2 rounded hover:bg-[#EC1E24] text-base">
        Start Now!
      </button>
    </div>
  </div>
);
